# Generated by Django 5.2.1 on 2025-06-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='session_type',
            field=models.CharField(choices=[('focus', 'Foco'), ('short_break', 'Pausa Curta'), ('long_break', 'Pausa Longa')], default='focus', max_length=20),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
